apiVersion: v1
kind: Namespace
metadata:
  name: gatewaydemo
  labels:
    app.kubernetes.io/part-of: vedmich-gatewaydemo
---
apiVersion: v1
kind: Namespace
metadata:
  name: gatewaydemo-cart
  labels:
    app.kubernetes.io/part-of: vedmich-gatewaydemo
